services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - FIREBASE_PROJECT_ID=fiapsub1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/fiapsub1-firebase-sdk.json
    volumes:
      - ./fiapsub1-firebase-sdk.json:/app/fiapsub1-firebase-sdk.json:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api-docs.json",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  app-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - FIREBASE_PROJECT_ID=fiapsub1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/fiapsub1-firebase-sdk.json
    volumes:
      - ./src:/app/src:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./.env:/app/.env:ro
      - ./fiapsub1-firebase-sdk.json:/app/fiapsub1-firebase-sdk.json:ro
    command: npm run start
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
